### ISSUE TITLE
Unicode characters may cause an exception

### ISSUE THREAD

**Issue by wevsty** [mjcaley/aiospamc#98]
If the data to be checked contains unciode characters, it will result in Content-Length mismatch.
I will give examples in Chinese.

Here is the test code：
```
import asyncio
from aiospamc import *


GTUBE = '''
From: wevsty <example@example.com>
Subject: =?UTF-8?B?5Lit5paH5rWL6K+V?=
Message-ID: <example@example.com>
Date: Tue, 15 Jan 2019 15:26:51 +0800
X-Mozilla-Draft-Info: internal/draft; vcard=0; receipt=0; DSN=0; uuencode=0;
 attachmentreminder=0; deliveryformat=4
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101
 Thunderbird/60.3.3
MIME-Version: 1.0
Content-Type: text/html; charset=gbk
Content-Transfer-Encoding: 8bit

这是Unicode文字.
This is Unicode characters.
'''

loop = asyncio.get_event_loop()
client = Client(host='127.0.0.1', port=783)
responses = loop.run_until_complete(client.ping())
responses = loop.run_until_complete(client.process(GTUBE))
print(responses)
```
Run the this code, SPAMD will return the following results
```
SPAMD/1.0 76 Bad header line: (Content-Length mismatch: Expected 484 bytes, got 492 bytes)
```

aiospamc will throw an exception
```
Exception for request (1422449975648)when composing response: <aiospamc.responses.Response object at 0x0000014B30A02FD0>
Traceback (most recent call last):
  File "D:\python_project\test\venv\lib\site-packages\aiospamc\client.py", line 247, in send
    self._raise_response_exception(response)
  File "D:\python_project\test\venv\lib\site-packages\aiospamc\client.py", line 169, in _raise_response_exception
    raise ProtocolException(response)
aiospamc.exceptions.ProtocolException: <aiospamc.responses.Response object at 0x0000014B30A02FD0>
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm_Community\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm_Community\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm_Community\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm_Community\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/python_project/test/test_aiospamc.py", line 26, in <module>
    responses = loop.run_until_complete(client.process(GTUBE))
  File "C:\Python\Python3\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "D:\python_project\test\venv\lib\site-packages\aiospamc\client.py", line 513, in process
    response = await self.send(request)
  File "D:\python_project\test\venv\lib\site-packages\aiospamc\client.py", line 30, in wrapper
    return await func(cls, request)
  File "D:\python_project\test\venv\lib\site-packages\aiospamc\client.py", line 47, in wrapper
    return await func(cls, request)
  File "D:\python_project\test\venv\lib\site-packages\aiospamc\client.py", line 247, in send
    self._raise_response_exception(response)
  File "D:\python_project\test\venv\lib\site-packages\aiospamc\client.py", line 169, in _raise_response_exception
    raise ProtocolException(response)
aiospamc.exceptions.ProtocolException: <aiospamc.responses.Response object at 0x0000014B30A02FD0>
```

**Comment by wevsty** [comment]
So,I think this problem occurs in the string to byte type conversion.
In Python 3 string is unicode type, 1 unicode character conversion bytes maybe not 1 byte.

for example:
len('中') = 1
len('中'.encode(‘utf-8’)) = 3

**Comment by wevsty** [comment]
I pull a commit that will fix the problem.
At the same time I added a note to the documentation and examples. Because this problem has bothered me.

If you are willing to merge into the project, I also recommend changing the version number so that users can get updates from pip

thank you very much.

**Comment by mjcaley** [comment]
Thanks for reporting this @wevsty.  I think you're right that that problem is in the bytes to string conversion.

I think the best approach might be to take the conversion code out entirely and let the user decide what to do with the bytes.  They'll probably make a better decision on what to do with it rather than a library making assumptions.

I've started to work on that in the meantime.

Thanks again for your contribution!  I'll see how it looks for removing the code and decide whether your pull request would be better or worse.

**Comment by wevsty** [comment]
My pull is just a temporary solution.Maybe changing the interface is a better solution.

Because in Python 3 string object can be easily converted to a bytes object, but the bytes object conversion cannot be easily converted to a string.

If I can't determine the encoding used by bytes, then the conversion will be a big problem.But the data we receive is often the bytes object.And the sender may not comply with the RFC standard and directly give you a unknow encoding the data.
But changing the interface is a big change, so I didn't change the code.

Thank you for your reply.

**Comment by tripleee** [comment]
There's a related, to my mind more serious, error when the data you pass in is not UTF-8.
Email messages are inherently bytes; there is no way to ensure that they are representable as a Python text object.

To repro, add
```
        ('TEST', b'Really \xbbinary stuff\n', [ContentLength(length=20)]),
```
to `tests/test_requests.py`.
